export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

//for all queries
export const GET_ALLQUERIES_START = "GET_ALLQUERIES_START"
export const GET_ALLQUERIES_SUCCESS = "GET_ALLQUERIES_SUCCESS";
export const GET_ALLQUERIES_FAIL = "GET_ALLQUERIES_FAIL";

export const GET_ALLJOBS_START = "GET_ALLJOBS_START";
export const GET_ALLJOBS_SUCCESS = "GET_ALLJOBS_SUCCESS";
export const GET_ALLJOBS_FAIL = "GET_ALLJOBS_FAIL";
export const POST_JOB = "POST_JOB";

export const GET_CONTRACTAPPLICANT_START = "GET_CONTRACTAPPLICANT_START";
export const GET_CONTRACTAPPLICANT_SUCCESS = "GET_CONTRACTAPPLICANT_SUCCESS";
export const GET_CONTRACTAPPLICANT_FAIL = "GET_CONTRACTAPPLICANT_FAIL";


