export const allJobsData = [
  {
    id: "1",
    jobId: "1000ID",
    jobTitle: "Java Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "Full Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "Publish",
    postedDate: "1/2/2021",
  },
  {
    id: "1",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "3",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "4",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "5",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "6",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "7",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "8",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "9",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "10",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
  {
    id: "11",
    jobId: "1000ID",
    jobTitle: "Node Developer",
    jobSubtitle: "Web Development",
    department: "Technology",
    jobType: "part Time",
    country: "Nepal",
    state: "Provience-1",
    city: "damak-6",
    description: "Requirement",
    publishBy: "Dipesh shrestha",
    visibility: "",
    postedDate: "1/2/2021",
  },
];
