export const contractData = [
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "notSeen",
    approvelStatus: "",
    postedDate: "2/2/2021",
  },
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "notSeen",
    approvelStatus: "",
    postedDate: "2/2/2021",
  },
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Reject",
    postedDate: "2/2/2021",
  },
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Reject",
    postedDate: "2/2/2021",
  },
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Accept",
    postedDate: "2/2/2021",
  },

  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Accept",
    postedDate: "2/2/2021",
  },
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Hold",
    postedDate: "2/2/2021",
  },
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Hold",
    postedDate: "2/2/2021",
  },
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Reject",
    postedDate: "2/2/2021",
  },
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    gmail: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Hold",
    postedDate: "2/2/2021",
  },
];
