export const internalData = [
  {
    jobTitle: "Java Develpoer",
    firstName: "Dipesh",
    middleName: "kumar",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "seen",
    approvelStatus: "Hold",
    appliedDate: "2/2/2021",
  },
  {
    jobTitle: "Web Develpoer",
    firstName: "Ram",
    middleName: "kumar",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    gender: "male",
    phone: "9816940668",
    country: "nepal",
    state: "provience-1",
    city: "damak-6",
    currentAddress: "Kathmandu",
    expectedSalary: "15000",
    senioritylevel: "internship",
    message: "hello",
    status: "notSeen",
    approvelStatus: "Accept",
    appliedDate: "2/2/2021",
  },
];
