import React from "react";

export const contactData = [
  {
    id: "1",
    firstName: "Dipesh",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "seen",
  },
  {
    id: "2",
    firstName: "Ram",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "3",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "4",
    firstName: "gita",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "5",
    firstName: "hari",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "seen",
  },
  {
    id: "3",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "4",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "5",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "6",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "7",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "8",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "9",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
  {
    id: "10",
    firstName: "Shayam",
    lastName: "Shrestha",
    email: "dipeshxtha129@gmail.com",
    phone: "9816940668",
    address: "damak-6, jhapa",
    subject: "small query",
    message: "hello world",
    status: "notSeen",
  },
];
