import { makeStyles } from "@material-ui/core/styles";

export const useStyle = makeStyles((theme) => ({
  root: {
    // color: "red",
    minHeight: "100vh",
    background: "linear-gradient(to bottom,  #4487A9 ,#B0C3BF )",
    display: "flex",
    justifyContent: "center",

    position: "relative",
  },
  centerGrid: {
    // border: "solid 1px red",
    backgroundColor: "white",
    position: "absolute",
    top: "15%",
    left: "20%",
    borderRadius: "10px",
    boxShadow: "0 8px 16px  rgba(0, 0, 0, 0.3)",
    // margin: "0 auto",
    height: "70vh",
    width: "60vw",
    color: "red",
    display: "flex",
    flexDirection: "row",
  },
  leftGrid: {
    borderRadius: "10px 0px 0px 10px",
    width: "50%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  login: {
    color: "#000000",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "35px",
    textAlign: "center",
  },
  email: {
    marginLeft: "5rem",
    //     height: "2rem",
  },
  rightGrid: {
    background: "#FF454F",
    borderRadius: "0px 10px 10px 0px ",
    width: "50%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItem: "center",
  },
  welcomeBack: {
    color: "#FFFFFF",
    // backgroundColor: "yellow",
    // fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "35px",
    textAlign: "center",
  },
  welcomeBackNote: {
    color: "rgba(255, 255, 255, 0.6)",
    fontStyle: "normal",
    textAlign: "center",
    fontWeight: "normal",
    fontSize: "18px",
    width: "80%",
    marginTop: "-1rem",
    marginLeft: "3.5rem",
  },
}));
